#!/bin/bash 

case $BLOCK_BUTTON in 
   2) st -e vim "$0" ;;
esac

home=$(df -h | awk '/dev\/sdb2/ { printf "%0.0f%", ($3/$2)*100 }')
root=$(df -h | awk '/dev\/root/ { printf "%0.0f%", ($3/$2)*100 }')
echo  $root ﳐ $home
